baseURL = "https://higebobo.github.io/hugo-cards/"
languageCode = "ja"
title = "Hugo Cards"
#publishDir = "docs"
theme = "hugo-cards"
#themesDir = "../.."
#themesDir = "./themes"
#paginate = 6
paginate = 60

#[taxonomies]
#  tag = "tags"

[params]
  builtBy = "bool"
  defaultImage = "gopher.jpg"

  facebook = "https://www.facebook.com/higebobo"
  quora = ""
  twitter = "https://twitter.com/higebobo"
  github = "https://github.com/higebobo"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  [params.copyright]
     name = "higebobo"
     link = "https://higebobo.netlify.com"

[[menu.main]]
url = "/tags"
name = "tags"
weight = 1
